# This file was generated by GoReleaser. DO NOT EDIT.
class Kubemqctl < Formula
  desc ""
  homepage ""
  version "2.0.0rc1"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/kubemq-io/kubemqctl/releases/download/v2.0.0rc1/kubemqctl_2.0.0rc1_darwin_amd64.tar.gz"
    sha256 "8ce22f2a7ca204f799a6eac637e5bb9528ade97352dccc12ed1769131d2a3d18"
  elsif OS.linux?
    if Hardware::CPU.intel?
      url "https://github.com/kubemq-io/kubemqctl/releases/download/v2.0.0rc1/kubemqctl_2.0.0rc1_linux_amd64.tar.gz"
      sha256 "65814a038cb398656df19e36e0f556e010561d7aed4bf6e346f6dd8258294bb1"
    end
  end

  def install
    bin.install "kubemqctl"
  end
end
