# This file was generated by GoReleaser. DO NOT EDIT.
class Kubemqctl < Formula
  desc ""
  homepage ""
  version "2.0.0rc1"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/kubemq-io/kubemqctl/releases/download/v2.0.0rc1/kubemqctl_2.0.0rc1_darwin_amd64.tar.gz"
    sha256 "78f36fedb67b8c4b50ccd93592759ce3431400dba31ba1c3486a0bf5cb243c56"
  elsif OS.linux?
    if Hardware::CPU.intel?
      url "https://github.com/kubemq-io/kubemqctl/releases/download/v2.0.0rc1/kubemqctl_2.0.0rc1_linux_amd64.tar.gz"
      sha256 "f1266aa42a050756758a84d8811cb9d999669a1ea1d2a96778696c0f5d46c186"
    end
  end

  def install
    bin.install "kubemqctl"
  end
end
