# github.com/go-task/task

version: '2'

vars:
  BINARY_NAME: kubemqctl
  VERSION: v3.0.1

tasks:
  default:
    cmds:
      - go mod tidy
      - go mod vendor
#      - golangci-lint run -E misspell,gosec
      - task: build_win
      - task: build_mac
      - task: build_linux_64
      - task: build_linux_32
  build_win:
    env:
      GOOS: windows
      GOARCH: amd64
    cmds:
      - go build -o "{{.BINARY_NAME}}.exe" -ldflags "-X main.version={{.VERSION}}"
      - go build -o "./bin/{{.BINARY_NAME}}.exe" -ldflags "-X main.version={{.VERSION}}"
  build_mac:
    env:
      GOOS: darwin
      GOARCH: amd64
    cmds:
      - go build -o "./bin/{{.BINARY_NAME}}_darwin_amd64" -ldflags "-X main.version={{.VERSION}}"
  build_linux_64:
    env:
      GOOS: linux
      GOARCH: amd64
    cmds:
      - go build -o "./bin/{{.BINARY_NAME}}_linux_amd64" -ldflags "-X main.version={{.VERSION}}"
  build_linux_32:
    env:
      GOOS: linux
      GOARCH: 386
    cmds:
      - go build -o "./bin/{{.BINARY_NAME}}_linux_386" -ldflags "-X main.version={{.VERSION}}"
