package kubemqdashboard

import "k8s.io/apimachinery/pkg/runtime"

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KubemqDashboard) DeepCopyInto(out *KubemqDashboard) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	out.Status = in.Status

}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KubemqDashboard.
func (in *KubemqDashboard) DeepCopy() *KubemqDashboard {
	if in == nil {
		return nil
	}
	out := new(KubemqDashboard)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *KubemqDashboard) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KubemqDashboardList) DeepCopyInto(out *KubemqDashboardList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]KubemqDashboard, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}

}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KubemqDashboardList.
func (in *KubemqDashboardList) DeepCopy() *KubemqDashboardList {
	if in == nil {
		return nil
	}
	out := new(KubemqDashboardList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *KubemqDashboardList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KubemqDashboardSpec) DeepCopyInto(out *KubemqDashboardSpec) {
	*out = *in
	if in.Prometheus != nil {
		in, out := &in.Prometheus, &out.Prometheus
		*out = new(PrometheusConfig)
		**out = **in
	}
	if in.Grafana != nil {
		in, out := &in.Grafana, &out.Grafana
		*out = new(GrafanaConfig)
		**out = **in
	}

}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KubemqDashboardSpec.
func (in *KubemqDashboardSpec) DeepCopy() *KubemqDashboardSpec {
	if in == nil {
		return nil
	}
	out := new(KubemqDashboardSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KubemqDashboardStatus) DeepCopyInto(out *KubemqDashboardStatus) {
	*out = *in

}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KubemqDashboardStatus.
func (in *KubemqDashboardStatus) DeepCopy() *KubemqDashboardStatus {
	if in == nil {
		return nil
	}
	out := new(KubemqDashboardStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PrometheusConfig) DeepCopyInto(out *PrometheusConfig) {
	*out = *in

}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PrometheusConfig.
func (in *PrometheusConfig) DeepCopy() *PrometheusConfig {
	if in == nil {
		return nil
	}
	out := new(PrometheusConfig)
	in.DeepCopyInto(out)
	return out
}
