kind: Namespace
apiVersion: v1
metadata:
  name: kubemq
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: kubemq-operator-kubemq-crb
subjects:
  - kind: ServiceAccount
    name: kubemq-operator
    namespace: kubemq
roleRef:
  kind: ClusterRole
  name: kubemq-operator
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: kubemq-cluster
  namespace: kubemq
rules:
  - apiGroups:
      - security.openshift.io
    resources:
      - securitycontextconstraints
    verbs:
      - use
      - delete
      - get
      - list
      - patch
      - update
      - watch
    resourceNames:
      - privileged
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: kubemq-cluster
  namespace: kubemq
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: kubemq-operator
  namespace: kubemq
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: kubemq-cluster-kubemq-rb
  namespace: kubemq
subjects:
  - kind: ServiceAccount
    name: kubemq-cluster
    namespace: kubemq
roleRef:
  kind: Role
  name: kubemq-cluster
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kubemq-operator
  namespace: kubemq
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kubemq-operator
  template:
    metadata:
      labels:
        app: kubemq-operator
    spec:
      serviceAccountName: kubemq-operator
      containers:
        - name: kubemq-operator
          image: docker.io/kubemq/kubemq-operator:latest
          command:
            - kubemq-operator
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
            - containerPort: 8090
          env:
            - name: WATCH_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: SOURCE
              value: "deploy"
            - name: DEBUG_MODE
              value: "false"
            - name: RELATED_IMAGE_KUBEMQ_CLUSTER
              value: "docker.io/kubemq/kubemq:latest"
            - name: RELATED_IMAGE_PROMETHEUS
              value: "prom/prometheus:latest"
            - name: RELATED_IMAGE_GRAFANA
              value: "grafana/grafana:latest"
            - name: KUBEMQ_VIEW_DASHBOARD_SOURCE
              value: "https://raw.githubusercontent.com/kubemq-io/kubemq-dashboard/master/dashboard.json"
            - name: OPERATOR_NAME
              value: "kubemq-operator"
            - name: KUBEMQ_LICENSE_MODE
              value: "COMMUNITY"
            - name: CONNECTOR_TARGETS_IMAGE
              value: "kubemq/kubemq-targets:latest"
            - name: CONNECTOR_SOURCES_IMAGE
              value: "kubemq/kubemq-sources:latest"
            - name: CONNECTOR_BRIDGES_IMAGE
              value: "kubemq/kubemq-bridges:latest"
            - name: CONNECTOR_TASKS_IMAGE
              value: "kubemq/kubemq-tasks:latest"
---
apiVersion: core.k8s.kubemq.io/v1beta1
kind: KubemqCluster
metadata:
  name: kubemq-cluster
  namespace: kubemq
spec:
  key: d7da1859-2924-4c45-8cf8-12c7e6b4b2c0
  replicas: 3
  standalone: false
  grpc:
    expose: LoadBalancer
